# To create a conda environment from this file, run the following command in Anaconda Prompt. Replace ENV_NAME with the desired name for the new environment, and FILE_NAME with the name of this file.
# conda env create --name ENV_NAME --file FILE_NAME.yml
# 
channels:
  - conda-forge
  - defaults
dependencies:
  # python version
  - python=3.8.11
  - pip=21.0.1 # conda. needed to install packages that only work when pip-installed.
  # pip-installed packages
  - pip:
    - streamlit==1.3.1 # pip. important package for simple web apps.